# Week 6 Project

## Ruotong Wang

<!-- leave this material as is -->
Compiled on `r date()`.

```{r include = FALSE}
library(DataComputing)
```
<!-- put your content after this line -->

Here is my content!
```{r cache = TRUE}
data_site <- 
  "http://tiny.cc/dcf/2014-Q4-Trips-History-Data-Small.rds" 
Trips <- readRDS(gzcon(url(data_site)))
```

```{r}
Trips %>%
  ggplot(aes(x = sdate)) + 
  geom_density(aes(fill = client), 
               color = NA, alpha = .4, position = "fill")
```
```{r}
Trips %>% 
  mutate(time_of_day = 
       lubridate::hour(sdate) + 
         lubridate::minute(sdate) / 60) %>%
   ggplot(aes(x = time_of_day)) + 
  geom_density(aes(fill = client), 
               color = NA, alpha = .4, position = "fill")
```
```{r}
Trips %>%
  mutate(time_of_day = 
       lubridate::hour(sdate) + 
         lubridate::minute(sdate) / 60,
       day_of_week=
           lubridate::wday(sdate, label=TRUE))%>%
  ggplot(aes(x = time_of_day)) + 
  geom_density(aes(fill = client), 
               color = NA, alpha = .4)+ facet_wrap( ~ day_of_week)
```
```{r}
Trips %>%
  mutate(time_of_day = 
       lubridate::hour(sdate) + 
         lubridate::minute(sdate) / 60,
       day_of_week=
           lubridate::wday(sdate, label=TRUE))%>%
  ggplot(aes(x = time_of_day)) + 
  geom_density(aes(fill = client), 
               color = NA, alpha = .4, position="stack")+ facet_wrap( ~ day_of_week)
```

