# Week 4 Project

## Ruotong Wang

<!-- leave this material as is -->
Compiled on `r date()`.

```{r include = FALSE}
library(DataComputing)
```
<!-- put your content after this line -->

1.
```{r}
DailyBirths<-
   Birthdays %>%
   group_by(date) %>%
   summarise(total=sum(births))
ggplot(data=DailyBirths,aes(x=date, y=total))+geom_point()
```
2.
```{r}
DailyBirths<-
DailyBirths %>%
   mutate(year=
            lubridate::year(date))%>%
   mutate(month=
            lubridate::month(date))%>%
   mutate(week=
            lubridate::week(date)) %>%
  mutate(day_of_week=
            lubridate::wday(date))
```

1).by week
```{r}
DailyBirthsweek<-
DailyBirths %>%
  group_by(week) %>%
  summarise(eachweek=sum(total))
```
```{r}
ggplot(data=DailyBirthsweek,aes(x=week, y=eachweek))+geom_point()
```

2). by month
```{r}
DailyBirthsmonth<-
DailyBirths %>%
  group_by(month) %>%
  summarise(eachmonth=sum(total))
```
```{r}
ggplot(data=DailyBirthsmonth,aes(x=month, y=eachmonth))+geom_point()
```

3.number of birth by day of week 
```{r}
DailyBirthsdweek<-
DailyBirths %>%
  group_by(day_of_week) %>%
  summarise(eachwday=sum(total))
```
```{r}
ggplot(data=DailyBirthsdweek,aes(x=day_of_week, y=eachwday))+geom_point()
```



4.
```{r}
MyTwoYears<-
DailyBirths %>%
  filter(year %in% c(1980,1981)) 
```
```{r}
ggplot(data=MyTwoYears,aes(x=date, y=total,color=day_of_week))+geom_point()
```
Sunday and Monday have the least children born.

5.
```{r}
Holidays <- read.csv("http://tiny.cc/dcf/US-Holidays.csv") %>%
  mutate(date = as.POSIXct(lubridate::dmy(date)))
```

6.







